// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJz7LkTtvPAd9xS8iy6GGeEusdwHlD5Pw',
    appId: '1:440778713834:web:d4bfec985fa15ebadc4593',
    messagingSenderId: '440778713834',
    projectId: 'restau-app-3b69b',
    authDomain: 'restau-app-3b69b.firebaseapp.com',
    storageBucket: 'restau-app-3b69b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3PHoOy877uAW8fTXXQuCuDYikjhw7cbE',
    appId: '1:440778713834:android:1776dfdf05f89970dc4593',
    messagingSenderId: '440778713834',
    projectId: 'restau-app-3b69b',
    storageBucket: 'restau-app-3b69b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAclLdR3vseNEYyVgDiBLDgR8whsn5tJd8',
    appId: '1:440778713834:ios:c7bb5475c8f2fa60dc4593',
    messagingSenderId: '440778713834',
    projectId: 'restau-app-3b69b',
    storageBucket: 'restau-app-3b69b.appspot.com',
    iosClientId: '440778713834-5qs7dq6v99hj1ula2jmmle4nv4vf9hsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.restauApp',
  );
}
